#!/bin/sh


PHP=`which php`
INCDIR=`dirname $0`
CASSEACMD=$0;

exec $PHP -C -q $INCARG\
    -d output_buffering=0 \
    -d variables_order=EGPCS \
    -d open_basedir="" \
    -d safe_mode=0 \
    -d register_argc_argv="On" \
    -d auto_prepend_file="" \
    -d auto_append_file="" \
    $INCDIR/_console/common/casseacmd.php "$@"
unset CASSEACMD

exit;
